---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/nifffty/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH 
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
